name: Release pipeline

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  create_tag:
    uses: ./.github/workflows/create_tag.yml
    secrets: inherit
  build:
    needs: create_tag
    uses: ./.github/workflows/build.yml
    secrets: inherit
  build_playdl_forked:
    needs: create_tag
    uses: ./.github/workflows/build-playdl-forked.yml
    secrets: inherit
  release:
    needs: [build, build_playdl_forked]
    uses: ./.github/workflows/release.yml
    secrets: inherit
