name: Docker build
on:
  release:
    types: [created, edited]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: destcom/stroycord
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tag: ${{ github.ref_name || inputs.tag }}
          tag_with_latest: true
          build_file: ./StroyCord.Dockerfile
